#!/usr/bin/env node

/**
 * NodePress Master Start Script
 * =============================
 * One command to rule them all.
 * Like WordPress: clone → npm i → npm start
 *
 * What this does:
 * 1. Checks environment (Node.js version, pnpm)
 * 2. Creates .env if missing (with secure auto-generated secrets)
 * 3. Starts Docker services (PostgreSQL, Redis, MinIO) if available
 * 4. If Docker unavailable, checks for local PostgreSQL
 * 5. Generates Prisma client
 * 6. Pushes database schema
 * 7. Seeds default data
 * 8. Starts dev server (API + Admin + Web)
 * 9. Opens browser to Install Wizard
 */

const { execSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const http = require('http');

const ROOT = __dirname;
const ENV_FILE = path.join(ROOT, '.env');
const ENV_EXAMPLE = path.join(ROOT, '.env.example');

// ============================================================
// UTILITY
// ============================================================
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
  bold: '\x1b[1m',
};

function log(msg, color) {
  console.log(`${color || colors.blue}[NodePress]${colors.reset} ${msg}`);
}

function logSuccess(msg) {
  console.log(`  ${colors.green}\u2705${colors.reset} ${msg}`);
}

function logWarn(msg) {
  console.log(`  ${colors.yellow}\u26a0\ufe0f${colors.reset} ${msg}`);
}

function logError(msg) {
  console.log(`  ${colors.red}\u274c${colors.reset} ${msg}`);
}

function run(cmd, opts = {}) {
  try {
    execSync(cmd, { stdio: opts.silent ? 'pipe' : 'inherit', cwd: ROOT, ...opts });
    return true;
  } catch (e) {
    if (!opts.silent) logError(`Command failed: ${e.message}`);
    return false;
  }
}

function runCapture(cmd) {
  try {
    return execSync(cmd, { stdio: 'pipe', cwd: ROOT, encoding: 'utf-8' }).trim();
  } catch {
    return '';
  }
}

function generateSecret(length) {
  return crypto
    .randomBytes(length)
    .toString('base64')
    .slice(0, length || 48);
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function portInUse(port) {
  return new Promise((resolve) => {
    const server = http.createServer();
    server.listen(port, '127.0.0.1', () => {
      server.close();
      resolve(false);
    });
    server.on('error', () => resolve(true));
  });
}

// ============================================================
// STEP 1: Check Environment
// ============================================================
async function checkEnvironment() {
  console.log('');
  console.log(`${colors.bold}${colors.cyan}============================================`);
  console.log('      \u{1F680} NodePress - Starting Up...');
  console.log('      WordPress-compatible CMS for Node.js');
  console.log(
    `${colors.bold}${colors.green}============================================${colors.reset}`,
  );
  console.log('');

  const nodeVersion = process.version;
  const major = parseInt(nodeVersion.slice(1).split('.')[0]);
  if (major < 20) {
    logError(`Node.js ${nodeVersion} detected. Version 20+ is required.`);
    log(`Download: ${colors.cyan}https://nodejs.org/${colors.reset}`);
    process.exit(1);
  }
  logSuccess(`Node.js ${nodeVersion}`);

  const npmVersion = runCapture('npm --version');
  if (npmVersion) logSuccess(`npm ${npmVersion}`);

  const pnpmVersion = runCapture('pnpm --version');
  if (!pnpmVersion) {
    logWarn('pnpm not found. Installing globally...');
    run('npm install -g pnpm@latest');
  } else {
    logSuccess(`pnpm ${pnpmVersion}`);
  }
}

// ============================================================
// STEP 2: Create .env if missing
// ============================================================
async function setupEnv() {
  if (fs.existsSync(ENV_FILE)) {
    logSuccess('.env file exists');
    return;
  }

  console.log('');
  log('\u{1F4DD} Creating .env configuration...');

  if (fs.existsSync(ENV_EXAMPLE)) {
    let env = fs.readFileSync(ENV_EXAMPLE, 'utf-8');

    env = env
      .replace(/^JWT_SECRET=.*$/m, `JWT_SECRET=${generateSecret()}`)
      .replace(/^JWT_REFRESH_SECRET=.*$/m, `JWT_REFRESH_SECRET=${generateSecret()}`)
      .replace(/^ENCRYPTION_KEY=.*$/m, `ENCRYPTION_KEY=${crypto.randomBytes(32).toString('hex')}`)
      .replace(/:6432\//g, ':5432/');

    fs.writeFileSync(ENV_FILE, env, 'utf-8');
  } else {
    const env = `# NodePress Configuration
# Auto-generated by start.js

JWT_SECRET=${generateSecret()}
JWT_REFRESH_SECRET=${generateSecret()}
ENCRYPTION_KEY=${crypto.randomBytes(32).toString('hex')}

DATABASE_URL=postgresql://nodepress:nodepress@localhost:5432/nodepress
DATABASE_DIRECT_URL=postgresql://nodepress:nodepress@localhost:5432/nodepress

REDIS_URL=redis://localhost:6379

APP_URL=http://localhost:3000
API_URL=http://localhost:3001
NEXT_PUBLIC_API_URL=http://localhost:3001
CORS_ORIGINS=http://localhost:3000,http://localhost:3001

S3_ENDPOINT=http://localhost:9000
S3_REGION=us-east-1
S3_ACCESS_KEY=nodepress
S3_SECRET_KEY=nodepress123
S3_BUCKET=nodepress-media
S3_PUBLIC_URL=http://localhost:9000/nodepress-media

NODE_ENV=development
NODEPRESS_DEBUG=true
LOG_LEVEL=debug

JWT_EXPIRY=15m
REFRESH_TOKEN_EXPIRY=7d
JWT_ISSUER=nodepress

MAINTENANCE_MODE=false
`;

    fs.writeFileSync(ENV_FILE, env, 'utf-8');
  }

  logSuccess('.env created with secure defaults');
}

// ============================================================
// STEP 3: Start Infrastructure
// ============================================================
async function startInfrastructure() {
  console.log('');
  log('\u{1F527} Checking infrastructure...');

  const hasDocker = runCapture('docker --version');

  if (hasDocker) {
    logSuccess('Docker available');

    const dockerRunning = run('docker info', { silent: true });

    if (dockerRunning) {
      log('Starting PostgreSQL, Redis, and MinIO containers...');

      const alreadyUp = runCapture('docker compose ps -q postgres 2>nul');

      if (alreadyUp) {
        logSuccess('Services already running from docker-compose.yml');
      } else {
        log('Pulling images and starting containers (first run may take a minute)...');
        const started = run('docker compose up -d postgres redis minio minio-init');
        if (started) {
          logSuccess('PostgreSQL, Redis, MinIO containers started');
          log('Waiting 5s for PostgreSQL to accept connections...');
          await sleep(5000);
        } else {
          logWarn('Docker Compose failed. Will try local database...');
        }
      }
    } else {
      logWarn('Docker is installed but the daemon is not running');
      console.log('');
      log('  \u{1F447} Please start Docker Desktop and run this command again:');
      console.log('');
      console.log('    1. Open Docker Desktop from your Start Menu / Applications');
      console.log('    2. Wait for the Docker icon to stop animating');
      console.log(`    3. Run:  ${colors.cyan}npm start${colors.reset}`);
      console.log('');
      log('Trying local PostgreSQL as fallback...');
    }
  } else {
    logWarn('Docker not found. Checking for local PostgreSQL...');
  }

  const dbConnected = run(
    'pnpm --filter @nodepressjs/db exec prisma db push --accept-data-loss --skip-generate 2>nul',
    { silent: true },
  );

  if (!dbConnected) {
    console.log('');
    logError('Cannot connect to PostgreSQL!');
    console.log('');
    console.log(`  ${colors.bold}Quick fixes:${colors.reset}`);
    console.log(
      `    1. Install Docker Desktop: ${colors.cyan}https://www.docker.com/products/docker-desktop/${colors.reset}`,
    );
    console.log(
      `    2. Install PostgreSQL:      ${colors.cyan}https://www.postgresql.org/download/${colors.reset}`,
    );
    console.log('    3. Update .env with your database connection string');
    console.log('');
    log('Make sure DATABASE_URL in .env points to a running PostgreSQL instance.');
    console.log('');
    return false;
  }

  return true;
}

// ============================================================
// STEP 4: Database Setup
// ============================================================
async function setupDatabase() {
  console.log('');
  log('\u{1F5C4}\uFE0F  Setting up database...');

  log('Generating Prisma client...');
  run('pnpm db:generate');
  logSuccess('Prisma client generated');

  log('Pushing schema to database...');
  const pushed = run('pnpm db:push');
  if (!pushed) {
    logWarn('db:push had issues. Trying direct prisma db push...');
    run('pnpm --filter @nodepressjs/db exec prisma db push --accept-data-loss');
  }
  logSuccess('Database schema ready');

  log('Seeding default data (admin user, settings, content types)...');
  run('pnpm db:seed');
  logSuccess('Default data seeded');
}

// ============================================================
// STEP 5: Start Dev Server
// ============================================================
async function startDevServer() {
  console.log('');
  console.log(`${colors.bold}${colors.green}============================================`);
  console.log(`${colors.bold}      \u2705 NodePress is Starting!`);
  console.log(
    `${colors.bold}${colors.green}============================================${colors.reset}`,
  );
  console.log('');
  console.log(
    `  ${colors.cyan}\u{1F310}${colors.reset} Admin Panel:  ${colors.bold}http://localhost:3000${colors.reset}`,
  );
  console.log(
    `  ${colors.cyan}\u{1F4D6}${colors.reset} API:          ${colors.bold}http://localhost:3001${colors.reset}`,
  );
  console.log(
    `  ${colors.cyan}\u{1F4DA}${colors.reset} API Docs:     ${colors.bold}http://localhost:3001/docs${colors.reset}`,
  );
  console.log('');
  console.log('  Follow the Install Wizard in your browser!');
  console.log('  5 Steps -> Create your admin account -> Start creating content!');
  console.log('');

  const dev = spawn('npx', ['turbo', 'run', 'dev', '--parallel'], {
    stdio: 'inherit',
    cwd: ROOT,
    shell: true,
  });

  setTimeout(() => {
    const platform = process.platform;
    const url = 'http://localhost:3000';
    if (platform === 'win32') {
      runCapture(`start "" "${url}"`);
    } else if (platform === 'darwin') {
      runCapture(`open "${url}"`);
    } else {
      runCapture(`xdg-open "${url}" 2>/dev/null`);
    }
  }, 10000);

  process.on('SIGINT', () => {
    console.log('');
    log('Shutting down...', colors.yellow);
    dev.kill('SIGTERM');
    process.exit(0);
  });

  process.on('SIGTERM', () => {
    dev.kill('SIGTERM');
    process.exit(0);
  });
}

// ============================================================
// MAIN
// ============================================================
async function main() {
  try {
    await checkEnvironment();
    await setupEnv();

    const infraOk = await startInfrastructure();
    if (!infraOk) {
      process.exit(1);
    }

    await setupDatabase();
    await startDevServer();
  } catch (err) {
    console.log('');
    logError(`Unexpected error: ${err.message}`);
    console.log('');
    process.exit(1);
  }
}

main();
